server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: SIRET-SERVICE
          uri: lb://SIRET-SERVICE
          predicates:
            - Path=/siret/**


